# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a9db7282a05b68cb7e4a701e57d828a38507995642152c083fddbcd3aad27ef04852d3d5337a0229dbd3b21907b5807ba5d0249f1e94761e5c7d892f436fe52

test:
  secret_key_base: e65c8b5205f2d3c515eb19a9eb7c365cf820d6dad2bdfd1e4286e5901a044d630a5ab788c8fda5cc30989d6b78aa5965d3be178aaaca2cd2e972cdb3f90e6433

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
